# This file contains all of the project's default configurations.

# Camera details and settings
camera:
  serial_number: "41948281"
  auto_exposure: True
  auto_timeout: 100000 #ms. Time we give camera to acquire an image before raising an error. Set long enough to give auto_exposure time to converge.
  exposure_time: 10000000 # (microseconds). Only utilised if auto_exposure == False
  timeout: 100000 #ms. Time we give camera to acquire an image before raising an error. Set it equal to 10 times the exposure_time by default.
  canonical_dtype: uint8 # The bit depth of frames captured by the sensor. Sensor in theory supports 8, 10, and 12-bit output. Numpy doesn't have 10 (12) bit containers, so
                         # if one of these values is chosen, make canonical_dtype equal to uint16 and leave the top 6 (4) bits unused
  